name: Run unit for other PHP plugins
on:
    pull_request:
        paths-ignore:
            - '**/changelog/**'

permissions: {}

jobs:
    test:
        runs-on: ubuntu-20.04
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v3

            - name: Setup WooCommerce Monorepo
              uses: ./.github/actions/setup-woocommerce-monorepo
              with:
                  php-version: '8.0'

            - name: Run WooCommerce Docs Tests
              run: pnpm test:unit
              working-directory: ./plugins/woocommerce-docs
